language: python
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
  
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
  allow_failures:
    - python: "pypy"
    - python: "pypy3"
      # pypy will just crash due to an incompatibility with lxml.
      # Newer versions of pypy seem to crash also, so we probably have to fix with a newer version of lxml
  
install:
 - pip install cybersource-rest-client-python

script:
  bash sample_code_runner.sh